### ISSUE TITLE
OpenCL library no provided

### ISSUE THREAD

**Issue by iago-suarez** [arrayfire/androidcl#1]
Hi, today I tried to buidl the project following your instructions but the ndk-build command return me this error:

```
iago@iago-S551LB:~/Escritorio/OpenCL/androidcl$ ndk-build
Android NDK: WARNING:jni/Android.mk:JNIProcessor: non-system libraries in linker flags: jni/libs/libOpenCL.so    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
[armeabi] Compile++ arm  : JNIProcessor <= processor.cpp
[armeabi] SharedLibrary  : libJNIProcessor.so
arm-linux-androideabi-g++: error: jni/libs/libOpenCL.so: No such file or directory
make: *** [obj/local/armeabi/libJNIProcessor.so] Error 1
```

I think the problem is that you do not provide the needed OpenCL library.

**Comment by 9prady9** [comment]
@iago-suarez 

I am assuming you found this repository via our blog post, if not please refer to the section **OpenCL** in the blog posted [here](http://arrayfire.com/getting-started-with-opencl-on-android/) where we have outlined how to obtain the `libOpenCL.so` file for your mobile/android device.

Back when we published the post, i used to have access to `Samsung Note3` and `Samsung Galaxy S5` which used to provide their OpenCL library files either on the device (`/system/vendor/lib/libOpenCL.so` - you to do `adb pull` to your dev machine to compile your application) or via their proprietary SDK. So, it is totally dependent on your mobile manufacturer to provide the OpenCL library.

**Comment by iago-suarez** [comment]
Ohh, thank you very much for your help. I've just readed the article and now I can compile your project!
